CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(25) NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "roles" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar,
  "level" varchar NOT NULL,
  "teacher" varchar(25) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "course_level" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "course_level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" varchar(20)
);

CREATE TABLE "courses_categoies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categories" int NOT NULL,
  "courses" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users" int NOT NULL,
  "courses" int NOT NULL
);


ALTER TABLE "Users" ADD FOREIGN KEY ("roles") REFERENCES "roles" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("name") REFERENCES "course_video" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("users") REFERENCES "Users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("courses") REFERENCES "courses" ("id");

ALTER TABLE "courses_categoies" ADD FOREIGN KEY ("courses") REFERENCES "courses" ("id");

ALTER TABLE "courses_categoies" ADD FOREIGN KEY ("categories") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_level") REFERENCES "course_level" ("id");


INSERT INTO users (name, email, password, age) VALUES ('Brandon','brandon@correo.com','brandon1234',28), ('Ian',	'ian@correo.com',	'ian1234',	30), ('Pedro',	'pedro@correo.com',	'pedro1234',	30);

INSERT INTO courses (title, description, level, teacher) VALUES ('react js'	'modulo react'	3	'Andres'), ('node js'	'modulo node js'	2	'Ian'), ('javascript'	'modulo js'	1	'Brenda');

INSERT INTO "course_level" (level) VALUES ('basic'),('intermediate'), ('advanced');

INSERT INTO "course_video" (title,url) VALUES ('Redux'	'www.redux.com'), ('Express'	'www.express.com'	), ('funciones'	'www.funciones.com');

INSERT INTO categoires (name) VALUES ('front-end basico'),('front-end framework'),('backend');

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');